# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."minecraft-tailscale-minecraft-server" = {
    image = "itzg/minecraft-server";
    environment = {
      "EULA" = "TRUE";
    };
    volumes = [
      "minecraft-tailscale_minecraftserver:/data:rw"
    ];
    dependsOn = [
      "tailscale"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network=container:tailscale"
    ];
  };
  systemd.services."podman-minecraft-tailscale-minecraft-server" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-volume-minecraft-tailscale_minecraftserver.service"
    ];
    requires = [
      "podman-volume-minecraft-tailscale_minecraftserver.service"
    ];
    partOf = [
      "podman-compose-minecraft-tailscale-root.target"
    ];
    wantedBy = [
      "podman-compose-minecraft-tailscale-root.target"
    ];
  };
  virtualisation.oci-containers.containers."tailscale" = {
    image = "tailscale/tailscale:latest";
    environment = {
      "TS_AUTHKEY" = "tskey-client-kURkWDyAYV11CNTRL-iXkP1D6WcHdYzDBDvQvLHdUUKuDrxAjH";
      "TS_STATE_DIR" = "/var/lib/tailscale";
      "TS_USERSPACE" = "FALSE";
    };
    volumes = [
      "/dev/net/tun:/dev/net/tun:rw"
      "/home/cale/Projects/Minecraft/docker/ts-minecraft/state:/var/lib/tailscale:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--cap-add=net_admin"
      "--cap-add=sys_module"
      "--hostname=tailscale-minecraft"
      "--network-alias=tailscale-client"
      "--network=minecraft-tailscale_default"
    ];
  };
  systemd.services."podman-tailscale" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-minecraft-tailscale_default.service"
    ];
    requires = [
      "podman-network-minecraft-tailscale_default.service"
    ];
    partOf = [
      "podman-compose-minecraft-tailscale-root.target"
    ];
    wantedBy = [
      "podman-compose-minecraft-tailscale-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-minecraft-tailscale_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f minecraft-tailscale_default";
    };
    script = ''
      podman network inspect minecraft-tailscale_default || podman network create minecraft-tailscale_default
    '';
    partOf = [ "podman-compose-minecraft-tailscale-root.target" ];
    wantedBy = [ "podman-compose-minecraft-tailscale-root.target" ];
  };

  # Volumes
  systemd.services."podman-volume-minecraft-tailscale_minecraftserver" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect minecraft-tailscale_minecraftserver || podman volume create minecraft-tailscale_minecraftserver
    '';
    partOf = [ "podman-compose-minecraft-tailscale-root.target" ];
    wantedBy = [ "podman-compose-minecraft-tailscale-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-minecraft-tailscale-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
