# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  options.octo-fiesta = {
    enable = lib.mkEnableOption "Enable octo-fiesta";
  };

  config = lib.mkIf config.octo-fiesta.enable {
    # Runtime
    virtualisation.podman = {
      enable = true;
      autoPrune.enable = true;
      dockerCompat = true;
    };

    # Enable container name DNS for all Podman networks.
    networking.firewall.interfaces = let
      matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
    in {
      "${matchAll}".allowedUDPPorts = [ 53 ];
    };

    virtualisation.oci-containers.backend = "podman";

    # Containers
    virtualisation.oci-containers.containers."octo-fiesta" = {
      image = "ghcr.io/v1ck3s/octo-fiesta:dev";
      environment = {
        "ASPNETCORE_ENVIRONMENT" = "Production";
        "Library__DownloadPath" = "/app/downloads";
        "SquidWTF__InstanceTimeoutSeconds" = "5";
        "SquidWTF__Quality" = "";
        "SquidWTF__Source" = "Tidal";
        "Subsonic__AutoUpgradeQuality" = "false";
        "Subsonic__CacheDurationHours" = "1";
        "Subsonic__DownloadMode" = "Album";
        "Subsonic__EnableExternalPlaylists" = "true";
        "Subsonic__ExplicitFilter" = "All";
        "Subsonic__MusicService" = "SquidWTF";
        "Subsonic__PlaylistsDirectory" = "playlists";
        "Subsonic__StorageMode" = "Permanent";
        "Subsonic__Url" = "http://localhost:4533";
      };
      volumes = [
        "/mnt/storage/media/OctoFiesta:/app/downloads:rw"
      ];
      ports = [
        "5274:8080/tcp"
      ];
      log-driver = "journald";
      extraOptions = [
        #"--network-alias=octo-fiesta"
        "--network=host"
      ];
    };
    systemd.services."podman-octo-fiesta" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "always";
      };
      after = [
        "podman-network-octo-fiesta_default.service"
      ];
      requires = [
        "podman-network-octo-fiesta_default.service"
      ];
      partOf = [
        "podman-compose-octo-fiesta-root.target"
      ];
      wantedBy = [
        "podman-compose-octo-fiesta-root.target"
      ];
    };

    # Networks
    systemd.services."podman-network-octo-fiesta_default" = {
      path = [ pkgs.podman ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStop = "podman network rm -f octo-fiesta_default";
      };
      script = ''
        podman network inspect octo-fiesta_default || podman network create octo-fiesta_default
      '';
      partOf = [ "podman-compose-octo-fiesta-root.target" ];
      wantedBy = [ "podman-compose-octo-fiesta-root.target" ];
    };

    # Root service
    # When started, this will automatically create all resources and start
    # the containers. When stopped, this will teardown all resources.
    systemd.targets."podman-compose-octo-fiesta-root" = {
      unitConfig = {
        Description = "Root target generated by compose2nix.";
      };
      wantedBy = [ "multi-user.target" ];
    };
  };
}
