# @generated by https://codeberg.org/goldstein/unflake
let
  indirect_deps = {
  };
  specs = {};
  deps = indirect_deps // builtins.mapAttrs (_: v:
    if builtins.typeOf v.outPath == "set" then
      v.outPath
    else if v?revision then
      { outPath = v.outPath; rev = v.revision; }
    else
      { outPath = v.outPath; }
  ) (import ./npins/default.nix);
  injections = rec {
    unflake_github_mescon_logitech-trueforce-linux-driver = {
      flake-utils = "unflake_github_numtide_flake-utils";
      nixpkgs = "unflake_github_nixos_nixpkgs_ref_nixos-unstable";
    };
    unflake_github_nix-systems_default = {
    };
    unflake_github_nixos_nixpkgs_ref_nixos-unstable = {
    };
    unflake_github_numtide_flake-utils = {
      systems = "unflake_github_nix-systems_default";
    };
  };
  inject = name: flake_path: subdir:
    let
      inputs = builtins.mapAttrs (_: dep: universe.${dep}) injections.${name} // {
        inherit self;
      };
      sourceInfo = deps.${name};
      outPath = "${sourceInfo.outPath}${subdir}";
      outputs = (import "${sourceInfo.outPath}/${flake_path}").outputs inputs;
      self = outputs // sourceInfo // {
        inherit inputs outputs outPath sourceInfo;
        _type = "flake";
        _flake = true;
      };
    in self;
  universe = rec {
    unflake_github_mescon_logitech-trueforce-linux-driver = inject "unflake_github_mescon_logitech-trueforce-linux-driver" "flake.nix" "";
    unflake_github_nix-systems_default = inject "unflake_github_nix-systems_default" "flake.nix" "";
    unflake_github_nixos_nixpkgs_ref_nixos-unstable = inject "unflake_github_nixos_nixpkgs_ref_nixos-unstable" "flake.nix" "";
    unflake_github_numtide_flake-utils = inject "unflake_github_numtide_flake-utils" "flake.nix" "";
  };
  inputs = {
    logitech-trueforce = universe.unflake_github_mescon_logitech-trueforce-linux-driver;
    nixpkgs = universe.unflake_github_nixos_nixpkgs_ref_nixos-unstable;
  };
in inputs // {
  withInputs = fn: let outputs = fn (inputs // { inherit self; }); self = outputs // {
    inherit inputs outputs;
    _type = "flake";
    outPath = builtins.toString ./.;
  }; in self;
  __functor = self: self.withInputs;
  self = throw "to use inputs.self, write `import ./unflake.nix (inputs: ...)`";
  _unflake = { inherit specs deps injections; };
}
