cale_passwd: ENC[AES256_GCM,data:qJq3T8LgMW4lIBCkQSAmN5Q9gzVbbrW6avw9SAQArLaGBpm1ea12CtqDxInKwuQXvV7+TCeY/5jfkNb+I+j/7Z589B9q7Ld/ow==,iv:qOp3Tq45q3adrpBWaX0Nral1I9cP3NuZL6jvESo3EsY=,tag:a7hAqxkukpU8IswvGdOMMA==,type:str]
garagefs_rpc_secret: ENC[AES256_GCM,data:wVctAxtnJM8ZUo6ntelSqZADXIoCwe+zmMahZzxEaeSkSl4dwi4HH0+5GlM/S1trdA1YQK6UiiZfjYClSKeJgQ==,iv:uftTb7aiHxShUOJudx0GeC9hOiIlcXRfgeIviosdepo=,tag:PR8iLhqCHy2cvlSJmhIf0g==,type:str]
paperless_sync_id: ENC[AES256_GCM,data:DTpgNOseqBedqhCs4QBeg25F9XDxzzOC5KwsS87yboJRNS8FDLoQkenuCBVq0VONIf4fGqgWdNrAurhewQ8m,iv:qH+O3gai2OYKUxKz5OwSmn76qsZadYe4/0eYthUsDvc=,tag:+DLJ0BQw7xasHXBK0BFpPQ==,type:str]
paperless_sync_passwd: ENC[AES256_GCM,data:Ljel+xD23I+UKfxAPZiYdyeAqCk=,iv:xGZ7vzWk5tbYS0L1lmEm+YHTyxTzwnSdQhQc7QtwvxQ=,tag:nsUKSJyQo/bfICgfwiPdFQ==,type:str]
restic-passphrase: ENC[AES256_GCM,data:JBfq1ka59HWF5rvI0yqNExLuYyxs1f/eqBL/Ke8l673nF85Dm4iPwyh1lXkp3Pkt,iv:DAFhaRU/uq1B8R2uTA6BGgntsZ/QmHYVbajVbF95i/0=,tag:T97uc15aa3ZEJHcU3/mWcQ==,type:str]
bucket: ENC[AES256_GCM,data:UcPN2hFYjDi6UcgxvYGo09tpLCI=,iv:6CHcNo/5uUr9ze1gAc2txXTUO+qglVpb2X6dlcmb4hY=,tag:QWmsPs7/+WH6pUTgHkjqiQ==,type:str]
keyid: ENC[AES256_GCM,data:L+5qMgJsyqpYTF547MOD0Eupvu6Iedxqkg==,iv:a91HeGr3YVixDsupyUC5W5yzXf12Ws1XxbULtBe4QyM=,tag:OHwSsmV+xCghHMpCQz8r8A==,type:str]
accesskey: ENC[AES256_GCM,data:eujhwydsGwnJVCMJs/YA0ht0L7WLoFKrlTBabGNP3w==,iv:2LRdeQb4drLe3QzLLRgjzyezfA6ij02l9x6QOcq7YTc=,tag:GxYGf9zWZNsEZiMa+mqyTg==,type:str]
factorio_user: ENC[AES256_GCM,data:Xlf9uNBKikCmjFQZoA==,iv:trJfnuefm1wXzJqHukiaWUkdcFLw5HPcHBBXnJqMTRk=,tag:V/QG8aBhCVDNr+jf0wj+ew==,type:str]
factorio_key: ENC[AES256_GCM,data:xfV8MlEbHWuwtDq//zxj0HqzIBs74L7YD21k75VL,iv:sdUUKxzJGmcPXaBKVEskEGli0TbOTPXG7ofG7tb1x/E=,tag:NdyquX7Qd4Wwb1Tuceh7Pg==,type:str]
tailscale-manage: ENC[AES256_GCM,data:gkV3OcPmPhpbqemnL4miGxvrFE9ysy6qh3sg3JerorQqK6QScONl7gqnKsO+MUCkuAcOL1QT0qf+vRDnRQ==,iv:nn85jH0W4uf+GZOt+UEyhlff56c5P+6Oq62HFE5qcqQ=,tag:D5rkFRS4o4+M1f3JnCJRbQ==,type:str]
syncthing-key: ENC[AES256_GCM,data:PhmwAq8Gy1eVDH95bHJAM2psh6xDmxRF6J0O2p0ZGjsOPh/dT6aun1yaexFFYhH8y2XgiYUbFYcBRDJzlQ/RH5vLMJz4dpXgXgKnyNaRQv1KSuQFt+da7p3BHfh79LjWdgyQNHWiIXw8NV/OCap7rWRu7A2ZIptpHFKI+4ogNCyzh8uVzBiUmtOihKNmvBPkh3LURlz1GVbx3DpF+HZPXx1PqHCGdGlhUB9tty82BETXYkJ3NUGEt77SqGWN5SrntsbTZhei7auhhSin7/cenkrMItTkf6Nmuj2ch9VwDdCju6qUO9Aqa1cb9KBLu4KUaYB+d0B0QDE64HVguc/i4JmYCHJ36MalK8vy5Z+18dUR8lwbGmdQP18GazVkQV8X,iv:vdE574ZTkKXVK7+bQAffKJMTZ4uvWnSGf1pDsor7cR0=,tag:amKkowj4t/eFiVEaei607Q==,type:str]
syncthing-cert: ENC[AES256_GCM,data:V7Q9lP0nn2Y6aOSaYcrLqPF8ea+OEjC2gqR79+2A3grd6okqnRP3TIZXu4EeqNV5wZzJU/vKjTUKu+yjRRezMd2hQUrQI7nIRzn3rzmHvU0sQMdukivQg5X4TjkUt9uSWhP92NJDJP4MV87AMDWIyV858lvUvefFiUx9bvFXr2uS/UVMrEn7S3h63x2NP1bn6sQ69XGQnMpuOlY0HGkolJt0ZPVOwRLLC/eBJ9eAhmEbHT8RS6/T8WMZYbZQ4xFZ6sZYU58Ta51xnv7mh9u6ILQj388Jqcwi8kgB03MQGW1SYE7x4Zw3fl5q/d2y7S/PKy5XQK9KYoyLGO4hZJRh+BvTM2MfDxumlQfBfUbyt7PsugmAhHZ97kZmR/34IcicXbNna7VRrDz8o0B3dMLwp6EyJ1ssVNpwsYK0qHYZQ8hKiQKe0uujW/8tJYw7Ug+xGBh+wVINngD7Nm51IPhyxssBXfxomJzJ0QjeIIgjI3vMRndCfQDZ+Z+6ZpKy+7SuzFiUVJrOKHAq7/bqma+6qAnkPVv0IphyZOyVO/b7u0BZpk2g0P8BmoWzkhYS0J4xGU2MQMjMaoRLSIBtgovcF/xxq27VuZXgE2VltpIQ3Sm/cmBQbO+MDWEfTbWPeLA9p+nPHsX6mg2nzm5ksq59ty3zc/wiBceLcT4gEJcrlIV/ojokNGvRT0vYGzhexDtD7RgZEe/6JUPU13xDgwmFXfe5ZHsSzs7ZHbt2WvscOsb2iwhpEuSxZn811I69A7F8yF85tUZASbzkJ+9UskMYmUSZcX3LoYdTzpUSkI3cP7oAxA7Xm4H/uPHi4/FIW8Tot58hPKLqwa0NvJng25aCEEyxHPfIc2mZPiOAxZYEF+vMYtROwVS2zCxkv24VeHxne7jufyenGZb5Wl9NdKay3lp51fn6GxlSDleTeAZRVWYMLr2hKEGEqntROk0Vd3vTjkXXrASw9znmqCRVfkdvvPC/leBHDRWm0Cq4otnFSAJCy8PyEWVYHF9wGD8avQJTo5Pqzrmd0HPT1NMRwxFZwCoNC35CEwfPO/g=,iv:EAPucWFvldP3U7ZlBAAv1IjYnO5ughxF1/FnuGqejyY=,tag:Bt6qGKgnzxIg/dr9p2yxzA==,type:str]
sops:
    age:
        - recipient: age1p90f0v3edg8urrk356f8mx47n23xda8yl2xwjqzevpdkq23t6dkstqzdmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZS1h4QStkK28rQmZ5cEc3
            VnhUUjhSVlduRDZlTTRDWnRXV3B3MHZEU2pnCmc4Ty9mWnl1M0tRK1lTSXBkQ2ta
            Q0JsbzZYblhUTmNHcitSNXl1NW9EbFkKLS0tIG10aExTMUVFUjdBOWJrNjNwUUIr
            cUVSaGFwZW1ad0JtdGVxbVE2U3FMancK+kH083uIuUP9NflT7ogpxAhH1hluuole
            ChcwZcawfOqV7IDKPmPlM8JhcmVaM2ryz6ygBmAm/Fc+ETvDUIdmNg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1paagl4g4tf6r6qu0rj5a3rthy4h69vt0enhk87l5vgvd2g8savmsva0pay
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZm1EeEpLdmE5RU5WWjU0
            UGlENDJTbUp2cEt2eUtGR0J2MmtaeXovbmpBClNib1NnR0NZdmV6b2RUMmVDZjM4
            c1pkWHVlNkpwK0NwU1lFemhGaDZTL3cKLS0tIHp6YkYzcDV1RllaQ3lVdWlSd0tK
            N1Z1NnI4enYvMWQ2aUlJT1dBbjZCMUkKDjWHZgUAZCiMuvuJz24VJGQwNYt4dVzE
            +AcvtmRcm25Dmta0h71C4Mr52vX8juaHq+okapRqadvOmcCt2bfYgg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1w0fdmrmgu26ez60cpra67jyu2ckcjj9z2sj77rzlguupvkyq0dwqmycyrl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjOUFQT2svQ1kxYXF6Uzh1
            cC9GaGFYWUpaTVZZNngwLzNLN3JCV1pDb3gwCjZyOVpKMWZIdmhhVTZacjhKWDMv
            TWV2K201VFZaS0FnMmJiWXpzNG54bWsKLS0tIGJkUDBJQ1JHS3FKOHJuY0NTQjFI
            MXljUGV0K3RoZnBEQm12UnZNanhYSUUKSrWnqtZxu/nKE0nu4msJmw9zLYMSp0ih
            OsP/aCOF/FGFf0qk1sifA+/htHb5t3BfQ2HMYrXGWoYGCZmkP6TEVQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19zdxtccg3z0psznlcj3mqa40gz50g0z6xfhfj9892488yy20df9qv0us28
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPQTYxbmpqY3VnWWsvYmlR
            VmZJejdIUjYrSngwbHB0QXZOWHFrQjFYQ2hvCkZCWEE4VHdEdk9qSVMrRE9ZbTgv
            WDUzOGNlOXcycUVRR21PTCtFV3czcHcKLS0tIElPQndXR2hUbUVaZWJrb1R0bVd1
            NXRqNFhsWVkzTHBNaTNWNjJrTGZsM0kKYiNtD9MGOOmoKlJeyEGr4FGHzXN5i3HU
            AcW71A1gZuabWnR4icTjtSLDLVIhS1dNMcpzyhx7Irj9KORaKHT6Gg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-13T04:29:45Z"
    mac: ENC[AES256_GCM,data:6VNFd3DXMdwWO9WqYL/3LCQfuqJv4PoR1BXFAwE1aAY1dSsH4o13gX1Q3eGuRcRl9zfzdxaeLunPML5fNlt5EqTH5nGBHBVH6kM6ioPjZxMe7CrqvnuahKffqVsXSr6SETyO34bVXwXukLkC7Kkuq/QvsdKG9wPOyEA+O0xoQqY=,iv:EtKUpIER1rn2egEdzdTv7AlG3BrIRF6Dpn94UiZ2q5M=,tag:PJF6ASbFUQ2QDfMMEWXwOA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
